// The gym (GYM-1, docs/design/room/spec.md, appendix): a fixed 10 x 10 map
// of 16 px tiles, the scenery on its walls, the eight pieces of equipment and
// the twelve stations. Every grid is 16 x 16, one letter per pixel, "." for
// transparent; the letters are the palette below, all of them design tokens.
// Pure data, so the room's script can draw from it too.
import type { Equipment } from "../lib/exercises.ts";

// k ink, n night, f floor, p panel, d deep, g green, e edge, m dim, w paper,
// l leaf, r resting
export const GYM_PALETTE: Record<string, string> = {
  k: "#0b2416",
  n: "#081a10",
  f: "#0f2a1a",
  p: "#143822",
  d: "#0f3d22",
  g: "#1f6b3a",
  e: "#3f8f5a",
  m: "#8fa896",
  w: "#e8f0d8",
  l: "#c8e66b",
  r: "#7cc6e8",
};

// k ink, n night, f floor, p panel, d deep, g green, e edge, m dim, w paper, l leaf, r resting
export const MAP: string[] = [
  "WMMMKPMMMW",
  "[...::...]",
  "[::::::::]",
  "[...::...]",
  "[::::::::]",
  "[...::...]",
  "[::::::::]",
  "C...::...L",
  "[...::...]",
  "____Ee____",
];

// slot 1 to 12, [x, y]
export const STATIONS: [number, number][] = [
  [1, 1], [3, 1], [6, 1], [8, 1], [1, 3], [3, 3], [6, 3], [8, 3], [1, 5], [3, 5], [6, 5], [8, 5],
];

export const TILES: Record<string, string[]> = {
  ".": [
    "pppppppppppppppp",
    "pfffffffffffffff",
    "pfffffnfffffffff",
    "pfffffffffffnfff",
    "pffnffffffffffff",
    "pfffffffffffffff",
    "pfffffffffnfffff",
    "pfffffffffffffff",
    "pffffffnffffffff",
    "pfffffffffffffff",
    "pfffffffffffffnf",
    "pffnffffffffffff",
    "pfffffffffffffff",
    "pfffffffnfffffff",
    "pfffffffffffffff",
    "pfffffffffffffff",
  ],
  ":": [
    "pppppppppppppppp",
    "pppppppppppppppp",
    "ppgppppppppgpppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppgppppppppgp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "ppgppppppppgpppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppgppppppppgp",
    "pppppppppppppppp",
  ],
  "W": [
    "kkkkkkkkkkkkkkkk",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
  ],
  "M": [
    "kkkkkkkkkkkkkkkk",
    "dddddddddddddddd",
    "dkkkkkkkkkkkkkkd",
    "dkmmmmmmmmmwmmkd",
    "dkmmmmmmmmwmmmkd",
    "dkmmmmmmmwmmmmkd",
    "dkmmmmmmwmmmmmkd",
    "dkmmmmmwmmmmwmkd",
    "dkmmmmwmmmmwmmkd",
    "dkmmmwmmmmwmmmkd",
    "dkmmmmmmmwmmmmkd",
    "dkmmmmmmmmmmmmkd",
    "dkkkkkkkkkkkkkkd",
    "dddddddddddddddd",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
  ],
  "K": [
    "kkkkkkkkkkkkkkkk",
    "dddddddddddddddd",
    "dddddkkkkkkddddd",
    "ddddkwwwwwwkdddd",
    "dddkwwwwkwwwkddd",
    "dddkwwwwkwwwkddd",
    "dddkwwwwkwwwkddd",
    "dddkwwwwkkkwkddd",
    "gggkwwwwwwwwkggg",
    "gggkwwwwwwwwkggg",
    "ddddkwwwwwwkdddd",
    "dddddkkkkkkddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
  ],
  "P": [
    "kkkkkkkkkkkkkkkk",
    "dddddddddddddddd",
    "ddkkkkkkkkkkkkdd",
    "ddkllllllllllkdd",
    "ddkllllllllllkdd",
    "ddklkkllllkklkdd",
    "ddklkkkkkkkklkdd",
    "ddklkkllllkklkdd",
    "ggkllllllllllkgg",
    "ggklkkkkkkkklkgg",
    "ddkllllllllllkdd",
    "ddklkkkkkllllkdd",
    "ddkkkkkkkkkkkkdd",
    "dddddddddddddddd",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
  ],
  "[": [
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kkkkkkkkkkkkkkgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kdddddddddddddgk",
    "kkkkkkkkkkkkkkgk",
  ],
  "]": [
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgkkkkkkkkkkkkkk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgdddddddddddddk",
    "kgkkkkkkkkkkkkkk",
  ],
  "_": [
    "kkkkkkkkkkkkkkkk",
    "gggggggggggggggg",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "kkkkkkkkkkkkkkkk",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "dddddddddddddddd",
    "kkkkkkkkkkkkkkkk",
  ],
  "E": [
    "kdkggggggggggggg",
    "kdkggggggggggggg",
    "kdkggggggggggggg",
    "kdkggggggggggggl",
    "kdkgggggggggggll",
    "kdkgggggggggglll",
    "kdkgggggggggllll",
    "kdkggggggggggggl",
    "kdkggggggggggggl",
    "kdkggggggggggggl",
    "kdkggggggggggggl",
    "kdkggggggggggggl",
    "kdkggggggggggggl",
    "kdkggggggggggggg",
    "kdkggggggggggggg",
    "kdkggggggggggggg",
  ],
  "e": [
    "gggggggggggggkdk",
    "gggggggggggggkdk",
    "gggggggggggggkdk",
    "lggggggggggggkdk",
    "llgggggggggggkdk",
    "lllggggggggggkdk",
    "llllgggggggggkdk",
    "lggggggggggggkdk",
    "lggggggggggggkdk",
    "lggggggggggggkdk",
    "lggggggggggggkdk",
    "lggggggggggggkdk",
    "lggggggggggggkdk",
    "gggggggggggggkdk",
    "gggggggggggggkdk",
    "gggggggggggggkdk",
  ],
};

// drawn over the wall tile named by base
export const SCENERY: Record<string, { base: string; grid: string[] }> = {
  C: { base: "[", grid: [
    "................",
    ".....kkkkkk.....",
    "....krrrrrrk....",
    "....krrwrrrk....",
    "....krrwrrrk....",
    "....krrrrrrk....",
    ".....kkrrkk.....",
    "...kkkkkkkkkk...",
    "...kwwwwwwwwk...",
    "...kwrkwwkrwk...",
    "...kwwwwwwwwk...",
    "...kmmmmmmmmk...",
    "...kmmmmmmmmk...",
    "...kmmmmmmmmk...",
    "...kmmmmmmmmk...",
    "...kkkkkkkkkk...",
  ] },
  L: { base: "]", grid: [
    "kkkkkkkkkkkkkkkk",
    "keeeeeekkeeeeeek",
    "kemmmmekkemmmmek",
    "keeeeeekkeeeeeek",
    "kemmmmekkemmmmek",
    "keeeeeekkeeeeeek",
    "keeeeeekkeeeeeek",
    "keeeewekkeweeeek",
    "keeeewekkeweeeek",
    "keeeeeekkeeeeeek",
    "keeeeeekkeeeeeek",
    "keeeeeekkeeeeeek",
    "keeeeeekkeeeeeek",
    "keeeeeekkeeeeeek",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
  ] },
};

export const GEAR: Record<Equipment, string[]> = {
  "treadmill": [
    "..kkkkkkkkkkkk..",
    "..kmmmmmmmmmmk..",
    "..kmkkkkkkkkmk..",
    "..kmkwwwwwwkmk..",
    "..kmkkkkkkkkmk..",
    "..kmmmmmmmmmmk..",
    "..kkmkkkkkkmkk..",
    "..kmmknnnnkmmk..",
    "..kmmknnnnkmmk..",
    "..kmmkkkkkkmmk..",
    "..kmmknnnnkmmk..",
    "..kmmknnnnkmmk..",
    "..kmmkkkkkkmmk..",
    "..kmmknnnnkmmk..",
    "..kmmknnnnkmmk..",
    "..kkkkkkkkkkkk..",
  ],
  "flat-bench": [
    "kkkk........kkkk",
    "kmmkwwwwwwwwkmmk",
    "kmmk.kk..kk.kmmk",
    "kkkk.kk..kk.kkkk",
    "....kkkkkkkk....",
    "....kggggggk....",
    "....kggggggk....",
    "....kggggggk....",
    "....kggggggk....",
    "....kggggggk....",
    "....kggggggk....",
    "....kggggggk....",
    "....kkkkkkkk....",
    ".....kmk.kmk....",
    ".....kmk.kmk....",
    ".....kkk.kkk....",
  ],
  "squat-rack": [
    "..kkkkkkkkkkkk..",
    "..kmmmmmmmmmmk..",
    "..kkkkkkkkkkkk..",
    "..kmk......kmk..",
    "kkkmk......kmkkk",
    "kmkmk......kmkmk",
    "kmwwwwwwwwwwwwmk",
    "kmkmk......kmkmk",
    "kkkmk......kmkkk",
    "..kmk......kmk..",
    "..kmk......kmk..",
    "..kmk......kmk..",
    "..kmk......kmk..",
    ".kkmkk....kkmkk.",
    ".kmmmk....kmmmk.",
    ".kkkkk....kkkkk.",
  ],
  "dumbbell-rack": [
    "................",
    ".kkk.kkkkkk.kkk.",
    ".kmkkkmkkmkkkmk.",
    ".kmwwwmkkmwwwmk.",
    ".kmkkkmkkmkkkmk.",
    ".kkk.kkkkkk.kkk.",
    "keeeeeeeeeeeeeek",
    "kkkkkkkkkkkkkkkk",
    ".kkk.kkkkkk.kkk.",
    ".kmkkkmkkmkkkmk.",
    ".kmwwwmkkmwwwmk.",
    ".kmkkkmkkmkkkmk.",
    ".kkk.kkkkkk.kkk.",
    "keeeeeeeeeeeeeek",
    "kkkkkkkkkkkkkkkk",
    ".kk..........kk.",
  ],
  "lifting-platform": [
    "kkkkkkkkkkkkkkkk",
    "keeeeeeeeeeeeeek",
    "keeeeeeeeeeeeeek",
    "keekkkeeeekkkeek",
    "keekmkeeeekmkeek",
    "keekmkeeeekmkeek",
    "keekmkkkkkkmkeek",
    "keekmwwwwwwmkeek",
    "keekmkkkkkkmkeek",
    "keekmkeeeekmkeek",
    "keekmkeeeekmkeek",
    "keekkkeeeekkkeek",
    "keeeeeeeeeeeeeek",
    "keeeeeeeeeeeeeek",
    "keeeeeeeeeeeeeek",
    "kkkkkkkkkkkkkkkk",
  ],
  "pull-up-bar": [
    ".kkkkkkkkkkkkkk.",
    ".kwwwwwwwwwwwwk.",
    ".kkkkkkkkkkkkkk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    ".kmk........kmk.",
    "kkmkk......kkmkk",
    "kmmmk......kmmmk",
    "kkkkk......kkkkk",
  ],
  "cable-machine": [
    "..kkkkkkkkkkkk..",
    "..kmmmmmmmmmmk..",
    "..kmkkkkkkkkmk..",
    "..kmk......kmk..",
    "..kmk.kkkk.kmk..",
    "..kmk.kwwk.kmk..",
    "..kmk.kkkk.kmk..",
    "..kmk.kwwk.kmk..",
    "..kmk.kkkk.kmk..",
    "..kmk.kwwk.kmk..",
    "..kmk.kkkk.kmk..",
    "..kmk.kwwk.kmk..",
    "..kmk.kkkk.kmk..",
    ".kkmkkkkkkkkmkk.",
    ".kmmmmmmmmmmmmk.",
    ".kkkkkkkkkkkkkk.",
  ],
  "exercise-mat": [
    "................",
    "...kkkkkkkkkk...",
    "...kggggggggk...",
    "...keeeeeeeek...",
    "...kggggggggk...",
    "...kggggggggk...",
    "...keeeeeeeek...",
    "...kggggggggk...",
    "...kggggggggk...",
    "...keeeeeeeek...",
    "...kggggggggk...",
    "...kggggggggk...",
    "...keeeeeeeek...",
    "...kggggggggk...",
    "...kkkkkkkkkk...",
    "................",
  ],
};

// your station: leaf corners
export const CLAIM: string[] = [
  "llll........llll",
  "l..............l",
  "l..............l",
  "l..............l",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "l..............l",
  "l..............l",
  "l..............l",
  "llll........llll",
];


// 3 x 5 digits for the empty bays' numbers
const DIGITS: Record<string, string[]> = {
  "0": ["eee", "e.e", "e.e", "e.e", "eee"],
  "1": [".e.", "ee.", ".e.", ".e.", "eee"],
  "2": ["eee", "..e", "eee", "e..", "eee"],
  "3": ["eee", "..e", ".ee", "..e", "eee"],
  "4": ["e.e", "e.e", "eee", "..e", "..e"],
  "5": ["eee", "e..", "eee", "..e", "eee"],
  "6": ["eee", "e..", "eee", "e.e", "eee"],
  "7": ["eee", "..e", ".e.", ".e.", ".e."],
  "8": ["eee", "e.e", "eee", "e.e", "eee"],
  "9": ["eee", "e.e", "eee", "..e", "eee"],
};

// An empty station: a dashed square in edge green on rows and columns 1 and
// 14, and its slot number, centred, from row 5.
export function bay(slot: number): string[] {
  const g = Array.from({ length: 16 }, () => Array(16).fill("."));
  const dash = (i: number) => i === 14 || ((i - 1) >> 1) % 2 === 0;
  for (let i = 1; i <= 14; i++) {
    if (!dash(i)) continue;
    g[1][i] = g[14][i] = g[i][1] = g[i][14] = "e";
  }
  const digits = String(slot).split("");
  const width = digits.length * 4 - 1;
  let x = Math.floor((16 - width) / 2);
  for (const d of digits) {
    DIGITS[d].forEach((row, dy) => [...row].forEach((ch, dx) => ch !== "." && (g[5 + dy][x + dx] = ch)));
    x += 4;
  }
  return g.map((r) => r.join(""));
}
